# Generated by Django 3.2.7 on 2021-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='activated',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
